Adding spanish translation to homepage
LRMD/ARManual pull request #17
Opened 2020-10-25 16:34 UTC by FernandoRoldan93

Readme file and `ARManual/.vuepress/config.js` translated to Spanish as asked in the issue #13

2020-10-26 21:09 UTC, domnantas requested changes
Thank you! Only one translation is missing

2020-10-26 21:09 UTC, domnantas commented on ARManual/es/README.md
> +actionText: Read →
`Read` needs translation too

2020-10-26 23:37 UTC, FernandoRoldan93 commented on ARManual/es/README.md
> +actionText: Read →
Ups, sorry! I have just add it 😅

2020-10-27 11:22 UTC, domnantas approved these changes
Gracias!

2020-10-27 11:24 UTC, merged

2020-10-27 11:40 UTC, FernandoRoldan93 commented
> Gracias!

Prašom! :slightly_smiling_face: